name: Verify format

on:
  pull_request: {}
  workflow_call: {}
  push:
    branches:
      - main

concurrency:
  group: "verify"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci --include dev
      - run: npx prettier .
